import { Constituent, AssistanceRequest, DisasterReliefEvent, QueueTicket, SocialCaseStudyReport, ActivityLog } from './types';

export const INITIAL_CONSTITUENTS: Constituent[] = [
  {
    id: 'CST-2026-001',
    fullName: 'Maria Santos Cruz',
    birthDate: '1955-04-12',
    age: 71,
    gender: 'Female',
    civilStatus: 'Widowed',
    sector: 'Senior Citizen',
    barangay: 'Poblacion',
    address: 'Purok 1, Barangay Poblacion, Bansud',
    contactNumber: '0917-555-0192',
    monthlyIncome: 2500,
    occupation: 'Retired / None',
    householdMembers: 2,
    is4PsBeneficiary: false,
    isSocialPensioner: true,
    idNumber: 'OSCA-2024-001',
    qrCodeData: 'MSWDO-CST-2026-001-MARIA-SANTOS-CRUZ',
    registeredDate: '2024-01-15',
    status: 'Active',
  },
  {
    id: 'CST-2026-002',
    fullName: 'Juan Dela Cruz',
    birthDate: '1982-08-25',
    age: 43,
    gender: 'Male',
    civilStatus: 'Married',
    sector: 'Indigent / 4Ps',
    barangay: 'Proper Bansud',
    address: 'Purok 3, Barangay Proper Bansud',
    contactNumber: '0918-444-2091',
    monthlyIncome: 4500,
    occupation: 'Construction Helper',
    householdMembers: 5,
    is4PsBeneficiary: true,
    isSocialPensioner: false,
    idNumber: '4PS-2023-8821',
    qrCodeData: 'MSWDO-CST-2026-002-JUAN-DELA-CRUZ',
    registeredDate: '2025-02-10',
    status: 'Active',
  },
  {
    id: 'CST-2026-003',
    fullName: 'Ana Reyes',
    birthDate: '1990-11-03',
    age: 35,
    gender: 'Female',
    civilStatus: 'Single',
    sector: 'PWD',
    barangay: 'Villa Pag-asa',
    address: 'Sitio Boundary, Barangay Villa Pag-asa',
    contactNumber: '0919-333-8821',
    monthlyIncome: 3000,
    occupation: 'Handicraft Weaver',
    householdMembers: 3,
    is4PsBeneficiary: false,
    isSocialPensioner: false,
    idNumber: 'PWD-2025-012',
    disabilityType: 'Visual Impairment',
    qrCodeData: 'MSWDO-CST-2026-003-ANA-REYES',
    registeredDate: '2025-06-01',
    status: 'Active',
  },
  {
    id: 'CST-2026-004',
    fullName: 'Ramon Garcia',
    birthDate: '1978-01-19',
    age: 48,
    gender: 'Male',
    civilStatus: 'Separated',
    sector: 'Solo Parent',
    barangay: 'Alcadesma',
    address: 'National Highway, Barangay Alcadesma',
    contactNumber: '0920-111-9988',
    monthlyIncome: 6000,
    occupation: 'Tricycle Driver',
    householdMembers: 4,
    is4PsBeneficiary: false,
    isSocialPensioner: false,
    idNumber: 'SP-2024-104',
    qrCodeData: 'MSWDO-CST-2026-004-RAMON-GARCIA',
    registeredDate: '2025-08-14',
    status: 'Active',
  },
  {
    id: 'CST-2026-005',
    fullName: 'Elena Torres',
    birthDate: '2004-09-30',
    age: 21,
    gender: 'Female',
    civilStatus: 'Single',
    sector: 'Child & Youth',
    barangay: 'Pag-asa',
    address: 'Zone 1, Barangay Pag-asa',
    contactNumber: '0921-777-3344',
    monthlyIncome: 0,
    occupation: 'Working Student',
    householdMembers: 4,
    is4PsBeneficiary: true,
    isSocialPensioner: false,
    idNumber: 'YTH-2025-089',
    qrCodeData: 'MSWDO-CST-2026-005-ELENA-TORRES',
    registeredDate: '2026-01-10',
    status: 'Active',
  },
];

export const INITIAL_ASSISTANCE_REQUESTS: AssistanceRequest[] = [
  {
    id: 'AICS-2026-001',
    constituentId: 'CST-2026-001',
    constituentName: 'Maria Santos Cruz',
    barangay: 'Poblacion',
    sector: 'Senior Citizen',
    assistanceType: 'Medical Assistance',
    institution: 'Bansud District Hospital / Oriental Mindoro Provincial Hospital',
    requestedAmount: 8000,
    recommendedAmount: 8000,
    disbursedAmount: 8000,
    dateRequested: '2026-08-01',
    status: 'Disbursed',
    situationNotes: 'Urgent hemodialysis session support and maintenance medication aid.',
    socialWorkerAssigned: 'Mrs. Maria Santos, RSW',
    checklist: {
      barangayIndigency: true,
      medicalCertificateOrHospitalBill: true,
      funeralContractOrDeathCertificate: false,
      schoolRegistrationOrID: false,
      validGovernmentID: true,
    },
  },
  {
    id: 'AICS-2026-002',
    constituentId: 'CST-2026-002',
    constituentName: 'Juan Dela Cruz',
    barangay: 'Proper Bansud',
    sector: 'Indigent / 4Ps',
    assistanceType: 'Food & Non-Food Aid',
    institution: 'MSWDO Bansud Relief Operations',
    requestedAmount: 3000,
    recommendedAmount: 3000,
    disbursedAmount: 3000,
    dateRequested: '2026-08-03',
    status: 'Disbursed',
    situationNotes: 'Emergency sustenance pack after river swell incident affecting household.',
    socialWorkerAssigned: 'Juan Dela Cruz, RSW',
    checklist: {
      barangayIndigency: true,
      medicalCertificateOrHospitalBill: false,
      funeralContractOrDeathCertificate: false,
      schoolRegistrationOrID: false,
      validGovernmentID: true,
    },
  },
  {
    id: 'AICS-2026-003',
    constituentId: 'CST-2026-003',
    constituentName: 'Ana Reyes',
    barangay: 'Villa Pag-asa',
    sector: 'PWD',
    assistanceType: 'Burial & Funeral Aid',
    institution: 'Bansud Memorial Funeral Services',
    requestedAmount: 12000,
    recommendedAmount: 10000,
    disbursedAmount: 0,
    dateRequested: '2026-08-05',
    status: 'Under Evaluation',
    situationNotes: 'Funeral assistance requested for deceased immediate family dependent.',
    socialWorkerAssigned: 'Grace Lim, RSW',
    checklist: {
      barangayIndigency: true,
      medicalCertificateOrHospitalBill: false,
      funeralContractOrDeathCertificate: true,
      schoolRegistrationOrID: false,
      validGovernmentID: true,
    },
  },
  {
    id: 'AICS-2026-004',
    constituentId: 'CST-2026-004',
    constituentName: 'Ramon Garcia',
    barangay: 'Alcadesma',
    sector: 'Solo Parent',
    assistanceType: 'Educational Support',
    institution: 'Oriental Mindoro State University',
    requestedAmount: 5000,
    recommendedAmount: 5000,
    disbursedAmount: 0,
    dateRequested: '2026-08-06',
    status: 'Approved for Payment',
    situationNotes: 'Tuition and book subsidy for dependent entering 2nd year college.',
    socialWorkerAssigned: 'Juan Dela Cruz, RSW',
    checklist: {
      barangayIndigency: true,
      medicalCertificateOrHospitalBill: false,
      funeralContractOrDeathCertificate: false,
      schoolRegistrationOrID: true,
      validGovernmentID: true,
    },
  },
  {
    id: 'AICS-2026-005',
    constituentId: 'CST-2026-005',
    constituentName: 'Elena Torres',
    barangay: 'Pag-asa',
    sector: 'Child & Youth',
    assistanceType: 'Emergency Cash Aid',
    institution: 'MSWDO Bansud Crisis Center',
    requestedAmount: 4000,
    recommendedAmount: 0,
    disbursedAmount: 0,
    dateRequested: '2026-08-07',
    status: 'Pending Intake',
    situationNotes: 'Emergency lodging and transportation assistance.',
    socialWorkerAssigned: 'Unassigned',
    checklist: {
      barangayIndigency: true,
      medicalCertificateOrHospitalBill: false,
      funeralContractOrDeathCertificate: false,
      schoolRegistrationOrID: false,
      validGovernmentID: false,
    },
  },
];

export const INITIAL_DISASTER_EVENTS: DisasterReliefEvent[] = [
  {
    id: 'DRRM-2026-01',
    eventName: 'Typhoon Relief Operations - Bansud Sector',
    dateDeclared: '2026-07-28',
    status: 'Active Response',
    familyFoodPacksStock: 1500,
    familyFoodPacksDistributed: 850,
    hygieneKitsStock: 1000,
    hygieneKitsDistributed: 620,
    evacuationCenters: [
      {
        id: 'EC-01',
        name: 'Bansud Municipal Gymnasium',
        barangay: 'Poblacion',
        capacityFamilies: 150,
        currentFamilies: 82,
        status: 'Open',
        contactPerson: 'Capt. Antonio Santos',
      },
    ],
  },
  {
    id: 'DRRM-2026-02',
    eventName: 'Barangay Proper Bansud Inundation Response',
    dateDeclared: '2026-08-02',
    status: 'Active Response',
    familyFoodPacksStock: 800,
    familyFoodPacksDistributed: 510,
    hygieneKitsStock: 500,
    hygieneKitsDistributed: 380,
    evacuationCenters: [
      {
        id: 'EC-02',
        name: 'Proper Bansud Elementary School Covered Court',
        barangay: 'Proper Bansud',
        capacityFamilies: 100,
        currentFamilies: 95,
        status: 'At Capacity',
        contactPerson: 'Brgy. Sec. Elena Perez',
      },
    ],
  },
  {
    id: 'DRRM-2026-03',
    eventName: 'Pre-positioning Standby - Bansud Coastal Barangays',
    dateDeclared: '2026-08-06',
    status: 'Recovery Phase',
    familyFoodPacksStock: 2500,
    familyFoodPacksDistributed: 200,
    hygieneKitsStock: 1500,
    hygieneKitsDistributed: 100,
    evacuationCenters: [],
  },
];

export const INITIAL_QUEUE_TICKETS: QueueTicket[] = [
  {
    id: 'TKT-101',
    ticketNumber: 'A-101',
    category: 'Priority (Senior/PWD/Pregnant)',
    constituentName: 'Maria Santos Cruz',
    purpose: 'Claiming Medical Disbursed Voucher',
    status: 'In Desk',
    issuedTime: '08:30 AM',
    deskAssigned: 2,
  },
  {
    id: 'TKT-102',
    ticketNumber: 'S-102',
    category: 'Priority (Senior/PWD/Pregnant)',
    constituentName: 'Juan Dela Cruz',
    purpose: 'Social Pension Booklet Renewal',
    status: 'Waiting',
    issuedTime: '08:45 AM',
  },
  {
    id: 'TKT-103',
    ticketNumber: 'R-103',
    category: 'Regular Intake',
    constituentName: 'Ana Reyes',
    purpose: 'Social Worker Interview & Evaluation',
    status: 'Waiting',
    issuedTime: '09:05 AM',
  },
  {
    id: 'TKT-104',
    ticketNumber: 'P-104',
    category: 'Inquiry & ID Reissuance',
    constituentName: 'Ramon Garcia',
    purpose: 'Solo Parent ID Application',
    status: 'Completed',
    issuedTime: '08:15 AM',
  },
];

export const INITIAL_REPORTS: SocialCaseStudyReport[] = [
  {
    id: 'SCSR-2026-001',
    constituentId: 'CST-2026-001',
    intakeId: 'AICS-2026-001',
    dateCreated: '2026-08-02',
    title: 'Social Case Study Report on Maria Santos Cruz (Medical Crisis)',
    problemPresented: 'Patient requires bi-weekly hemodialysis therapy with severe financial deficit following bereavement.',
    familyBackground: 'Client is 71-year-old widowed senior citizen residing with unemployed granddaughter in Barangay Poblacion, Bansud, Oriental Mindoro.',
    evaluativeAssessment: 'Client is indigent senior citizen dependent on social pension. Household income falls well below food poverty line.',
    recommendation: 'Recommend release of PHP 8,000 AICS Medical Financial Aid under DSWD Memorandum Circular No. 16.',
    socialWorkerName: 'Mrs. Maria Santos, RSW',
    caseWorkerSignatureTitle: 'Registered Social Worker (RSW) / Case Manager',
  },
  {
    id: 'SCSR-2026-002',
    constituentId: 'CST-2026-003',
    intakeId: 'AICS-2026-003',
    dateCreated: '2026-08-05',
    title: 'Social Case Study Report on Ana Reyes (Burial Assistance)',
    problemPresented: 'Funeral and burial expense burden following unexpected passing of breadwinner.',
    familyBackground: 'Client is single PWD living with 2 minor dependents in Barangay Villa Pag-asa, Bansud, Oriental Mindoro.',
    evaluativeAssessment: 'Client belongs to PWD sector with limited monthly income.',
    recommendation: 'Recommend release of PHP 10,000 Burial Assistance to funeral home provider.',
    socialWorkerName: 'Grace Lim, RSW',
    caseWorkerSignatureTitle: 'Registered Social Worker (RSW)',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'LOG-001',
    timestamp: new Date().toISOString(),
    action: 'CREATE',
    module: 'Constituents',
    description: 'Registered constituent profile for Maria Santos Cruz (Brgy. Poblacion, Bansud)',
    targetId: 'CST-2026-001',
    performedBy: 'Mrs. Maria Santos, RSW',
  },
  {
    id: 'LOG-002',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    action: 'DISBURSE',
    module: 'AICS Assistance',
    description: 'Disbursed PHP 8,000 Medical Assistance for Maria Santos Cruz [Status: Disbursed]',
    targetId: 'AICS-2026-001',
    performedBy: 'Mrs. Maria Santos, RSW',
  },
  {
    id: 'LOG-003',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    action: 'UPDATE',
    module: 'Queue',
    description: 'Queue ticket A-101 (Maria Santos Cruz) changed status to In Desk',
    targetId: 'TKT-101',
    performedBy: 'Duty Social Worker',
  },
];
